//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propImage
    {
        public int imageID { get; set; }
        public byte[] propImage1 { get; set; }
        public byte[] propImageThumb { get; set; }
        public Nullable<int> propID_FK { get; set; }
        public Nullable<int> propAgentID_FK { get; set; }
    
        public virtual property property { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
