//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public property()
        {
            this.propImages = new HashSet<propImage>();
        }
    
        public int PropID { get; set; }
        public string pName { get; set; }
        public Nullable<int> pType { get; set; }
        public string propFor { get; set; }
        public Nullable<int> pFloors { get; set; }
        public Nullable<int> pPrice { get; set; }
        public Nullable<int> pNoofRooms { get; set; }
        public Nullable<int> pNoofBeds { get; set; }
        public Nullable<int> pSizeSquare { get; set; }
        public Nullable<int> pCityID_FK { get; set; }
        public string pAddress { get; set; }
        public string pPostCode { get; set; }
        public string pDescription { get; set; }
        public Nullable<int> pAgentID_FK { get; set; }
        public Nullable<System.DateTime> pPublicationDate { get; set; }
        public Nullable<System.DateTime> pAvailableFrom { get; set; }
        public Nullable<System.DateTime> pLastUpdated { get; set; }
        public Nullable<bool> pActivationStatus { get; set; }
        public Nullable<bool> pActivationAdmin { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<propImage> propImages { get; set; }
        public virtual user user { get; set; }
    }
}
