//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.properties = new HashSet<property>();
            this.propImages = new HashSet<propImage>();
            this.propImages1 = new HashSet<propImage>();
            this.propImages2 = new HashSet<propImage>();
            this.propImages3 = new HashSet<propImage>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string uEmail { get; set; }
        public string uPassword { get; set; }
        public string uPhone { get; set; }
        public Nullable<int> uCityID_FK { get; set; }
        public Nullable<bool> uActivation { get; set; }
        public Nullable<bool> uActivAdmin { get; set; }
        public Nullable<System.Guid> uGuid { get; set; }
        public byte[] uLogo { get; set; }
        public Nullable<System.DateTime> uDateCreated { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<property> properties { get; set; }
        public virtual ICollection<propImage> propImages { get; set; }
        public virtual ICollection<propImage> propImages1 { get; set; }
        public virtual ICollection<propImage> propImages2 { get; set; }
        public virtual ICollection<propImage> propImages3 { get; set; }
    }
}
